from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Capture for user")
        MainWindow.resize(800, 480)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.showFullScreen()
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AddItemToDb_ProgramName = QtWidgets.QLabel(self.centralwidget)
        self.AddItemToDb_ProgramName.setEnabled(True)
        self.AddItemToDb_ProgramName.setGeometry(QtCore.QRect(125, 50, 550, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.AddItemToDb_ProgramName.setFont(font)
        self.AddItemToDb_ProgramName.setFocusPolicy(QtCore.Qt.NoFocus)
        self.AddItemToDb_ProgramName.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.AddItemToDb_ProgramName.setAutoFillBackground(False)
        self.AddItemToDb_ProgramName.setTextFormat(QtCore.Qt.RichText)
        self.AddItemToDb_ProgramName.setAlignment(QtCore.Qt.AlignCenter)
        self.AddItemToDb_ProgramName.setObjectName("AddItemToDb_ProgramName")
        self.AddItemToDb_backButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddItemToDb_backButton.setGeometry(QtCore.QRect(650, 390, 70, 40))
        self.AddItemToDb_backButton.setMinimumSize(QtCore.QSize(70, 40))
        self.AddItemToDb_backButton.setMaximumSize(QtCore.QSize(70, 40))
        self.AddItemToDb_backButton.setObjectName("AddItemToDb_backButton")
        self.AddItemToDb_userLabel = QtWidgets.QLabel(self.centralwidget)
        self.AddItemToDb_userLabel.setGeometry(QtCore.QRect(150, 160, 190, 60))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.AddItemToDb_userLabel.setFont(font)
        self.AddItemToDb_userLabel.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.AddItemToDb_userLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AddItemToDb_userLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.AddItemToDb_userLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.AddItemToDb_userLabel.setLineWidth(5)
        self.AddItemToDb_userLabel.setObjectName("AddItemToDb_userLabel")
        self.AddItemToDb_userCodeLabel = QtWidgets.QLabel(self.centralwidget)
        self.AddItemToDb_userCodeLabel.setGeometry(QtCore.QRect(320, 230, 190, 60))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.AddItemToDb_userCodeLabel.setFont(font)
        self.AddItemToDb_userCodeLabel.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.AddItemToDb_userCodeLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AddItemToDb_userCodeLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.AddItemToDb_userCodeLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.AddItemToDb_userCodeLabel.setLineWidth(5)
        self.AddItemToDb_userCodeLabel.setObjectName("AddItemToDb_userCodeLabel")
        self.AddItemToDb_captureLHandButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddItemToDb_captureLHandButton.setGeometry(QtCore.QRect(150, 330, 210, 40))
        self.AddItemToDb_captureLHandButton.setMinimumSize(QtCore.QSize(210, 40))
        self.AddItemToDb_captureLHandButton.setMaximumSize(QtCore.QSize(210, 40))
        self.AddItemToDb_captureLHandButton.setObjectName("AddItemToDb_captureLHandButton")
        self.AddItemToDb_captureRHandButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddItemToDb_captureRHandButton.setGeometry(QtCore.QRect(440, 330, 210, 40))
        self.AddItemToDb_captureRHandButton.setMinimumSize(QtCore.QSize(210, 40))
        self.AddItemToDb_captureRHandButton.setMaximumSize(QtCore.QSize(210, 40))
        self.AddItemToDb_captureRHandButton.setObjectName("AddItemToDb_captureRHandButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Capture for user", "Capture for user"))
        self.AddItemToDb_ProgramName.setText(_translate("Capture for user", "Insert item to database"))
        self.AddItemToDb_backButton.setText(_translate("Capture for user", "Back"))
        self.AddItemToDb_userLabel.setText(_translate("Capture for user", "User code:"))
        self.AddItemToDb_userCodeLabel.setText(_translate("Capture for user", ""))
        self.AddItemToDb_captureLHandButton.setText(_translate("Capture for user", "Capture LEFT HAND"))
        self.AddItemToDb_captureRHandButton.setText(_translate("Capture for user", "Capture RIGHT HAND"))
