from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Insert new user")
        MainWindow.resize(800, 480)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.showFullScreen()
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.addItemToDb_ProgramName = QtWidgets.QLabel(self.centralwidget)
        self.addItemToDb_ProgramName.setEnabled(True)
        self.addItemToDb_ProgramName.setGeometry(QtCore.QRect(125, 50, 550, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.addItemToDb_ProgramName.setFont(font)
        self.addItemToDb_ProgramName.setFocusPolicy(QtCore.Qt.NoFocus)
        self.addItemToDb_ProgramName.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.addItemToDb_ProgramName.setAutoFillBackground(False)
        self.addItemToDb_ProgramName.setTextFormat(QtCore.Qt.RichText)
        self.addItemToDb_ProgramName.setAlignment(QtCore.Qt.AlignCenter)
        self.addItemToDb_ProgramName.setObjectName("addItemToDb_ProgramName")
        self.addItemToDb_backButton = QtWidgets.QPushButton(self.centralwidget)
        self.addItemToDb_backButton.setGeometry(QtCore.QRect(650, 390, 70, 40))
        self.addItemToDb_backButton.setMinimumSize(QtCore.QSize(70, 40))
        self.addItemToDb_backButton.setMaximumSize(QtCore.QSize(70, 40))
        self.addItemToDb_backButton.setObjectName("addItemToDb_backButton")
        self.addItemToDb_userCodeLabel = QtWidgets.QLabel(self.centralwidget)
        self.addItemToDb_userCodeLabel.setGeometry(QtCore.QRect(125, 200, 550, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.addItemToDb_userCodeLabel.setFont(font)
        self.addItemToDb_userCodeLabel.setObjectName("addItemToDb_userCodeLabel")
        self.addItemToDb_codeInput = QtWidgets.QLineEdit(self.centralwidget)
        self.addItemToDb_codeInput.setGeometry(QtCore.QRect(125, 240, 550, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.addItemToDb_codeInput.setFont(font)
        self.addItemToDb_codeInput.setText("")
        self.addItemToDb_codeInput.setObjectName("addItemToDb_codeInput")
        self.addItemToDb_searchUserButton = QtWidgets.QPushButton(self.centralwidget)
        self.addItemToDb_searchUserButton.setGeometry(QtCore.QRect(280, 320, 210, 40))
        self.addItemToDb_searchUserButton.setMinimumSize(QtCore.QSize(210, 40))
        self.addItemToDb_searchUserButton.setMaximumSize(QtCore.QSize(210, 40))
        self.addItemToDb_searchUserButton.setObjectName("addItemToDb_searchUserButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Insert new user", "MainWindow"))
        self.addItemToDb_ProgramName.setText(_translate("Insert new user", "Insert item to database"))
        self.addItemToDb_backButton.setText(_translate("Insert new user", "Back"))
        self.addItemToDb_userCodeLabel.setText(_translate("Insert new user", "User code:"))
        self.addItemToDb_searchUserButton.setText(_translate("Insert new user", "Search user"))
