from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Search users")
        MainWindow.resize(800, 480)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.showFullScreen()
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AddItemToDb_ProgramName = QtWidgets.QLabel(self.centralwidget)
        self.AddItemToDb_ProgramName.setEnabled(True)
        self.AddItemToDb_ProgramName.setGeometry(QtCore.QRect(125, 50, 550, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.AddItemToDb_ProgramName.setFont(font)
        self.AddItemToDb_ProgramName.setFocusPolicy(QtCore.Qt.NoFocus)
        self.AddItemToDb_ProgramName.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.AddItemToDb_ProgramName.setAutoFillBackground(False)
        self.AddItemToDb_ProgramName.setTextFormat(QtCore.Qt.RichText)
        self.AddItemToDb_ProgramName.setAlignment(QtCore.Qt.AlignCenter)
        self.AddItemToDb_ProgramName.setObjectName("AddItemToDb_ProgramName")
        self.AddItemToDb_backButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddItemToDb_backButton.setGeometry(QtCore.QRect(650, 390, 70, 40))
        self.AddItemToDb_backButton.setMinimumSize(QtCore.QSize(70, 40))
        self.AddItemToDb_backButton.setMaximumSize(QtCore.QSize(70, 40))
        self.AddItemToDb_backButton.setObjectName("AddItemToDb_backButton")
        self.AddItemToDb_nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.AddItemToDb_nameLabel.setGeometry(QtCore.QRect(125, 200, 550, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AddItemToDb_nameLabel.setFont(font)
        self.AddItemToDb_nameLabel.setObjectName("AddItemToDb_nameLabel")
        self.AddItemToDb_nameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.AddItemToDb_nameInput.setGeometry(QtCore.QRect(125, 240, 550, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AddItemToDb_nameInput.setFont(font)
        self.AddItemToDb_nameInput.setText("")
        self.AddItemToDb_nameInput.setObjectName("AddItemToDb_nameInput")
        self.AddItemToDb_searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddItemToDb_searchButton.setGeometry(QtCore.QRect(280, 320, 210, 40))
        self.AddItemToDb_searchButton.setMinimumSize(QtCore.QSize(210, 40))
        self.AddItemToDb_searchButton.setMaximumSize(QtCore.QSize(210, 40))
        self.AddItemToDb_searchButton.setObjectName("AddItemToDb_searchButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Search users", "MainWindow"))
        self.AddItemToDb_ProgramName.setText(_translate("Search users", "Database maintenance"))
        self.AddItemToDb_backButton.setText(_translate("Search users", "Back"))
        self.AddItemToDb_nameLabel.setText(_translate("Search users", "Search for Legal Name or code:"))
        self.AddItemToDb_searchButton.setText(_translate("Search users", "Seach"))
