from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Results")
        MainWindow.resize(800, 480)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.showFullScreen()
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.DbMaintenance_query_ProgramName = QtWidgets.QLabel(self.centralwidget)
        self.DbMaintenance_query_ProgramName.setEnabled(True)
        self.DbMaintenance_query_ProgramName.setGeometry(QtCore.QRect(125, 50, 550, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.DbMaintenance_query_ProgramName.setFont(font)
        self.DbMaintenance_query_ProgramName.setFocusPolicy(QtCore.Qt.NoFocus)
        self.DbMaintenance_query_ProgramName.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.DbMaintenance_query_ProgramName.setAutoFillBackground(False)
        self.DbMaintenance_query_ProgramName.setTextFormat(QtCore.Qt.RichText)
        self.DbMaintenance_query_ProgramName.setAlignment(QtCore.Qt.AlignCenter)
        self.DbMaintenance_query_ProgramName.setObjectName("DbMaintenance_query_ProgramName")
        self.DbMaintenance_query_backButton = QtWidgets.QPushButton(self.centralwidget)
        self.DbMaintenance_query_backButton.setGeometry(QtCore.QRect(650, 390, 70, 40))
        self.DbMaintenance_query_backButton.setMinimumSize(QtCore.QSize(70, 40))
        self.DbMaintenance_query_backButton.setMaximumSize(QtCore.QSize(70, 40))
        self.DbMaintenance_query_backButton.setObjectName("DbMaintenance_query_backButton")
        self.DbMaintenance_query_resultsLabel = QtWidgets.QLabel(self.centralwidget)
        self.DbMaintenance_query_resultsLabel.setGeometry(QtCore.QRect(125, 150, 550, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.DbMaintenance_query_resultsLabel.setFont(font)
        self.DbMaintenance_query_resultsLabel.setObjectName("DbMaintenance_query_resultsLabel")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(110, 200, 571, 181))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 569, 179))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.tableView = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.tableView.setGeometry(QtCore.QRect(0, 0, 571, 180))
        self.tableView.setObjectName("tableView")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Results", "MainWindow"))
        self.DbMaintenance_query_ProgramName.setText(_translate("Results", "Database maintenance"))
        self.DbMaintenance_query_backButton.setText(_translate("Results", "Back"))
        self.DbMaintenance_query_resultsLabel.setText(_translate("Results", "Search for Legal Name or code:"))
