from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Insert new user")
        MainWindow.resize(800, 480)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.showFullScreen()
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.InserNewUser_ProgramName = QtWidgets.QLabel(self.centralwidget)
        self.InserNewUser_ProgramName.setEnabled(True)
        self.InserNewUser_ProgramName.setGeometry(QtCore.QRect(200, 50, 400, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.InserNewUser_ProgramName.setFont(font)
        self.InserNewUser_ProgramName.setFocusPolicy(QtCore.Qt.NoFocus)
        self.InserNewUser_ProgramName.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.InserNewUser_ProgramName.setAutoFillBackground(False)
        self.InserNewUser_ProgramName.setTextFormat(QtCore.Qt.RichText)
        self.InserNewUser_ProgramName.setAlignment(QtCore.Qt.AlignCenter)
        self.InserNewUser_ProgramName.setObjectName("InserNewUser_ProgramName")
        self.InserNewUser_insertUserButton = QtWidgets.QPushButton(self.centralwidget)
        self.InserNewUser_insertUserButton.setGeometry(QtCore.QRect(280, 370, 210, 40))
        self.InserNewUser_insertUserButton.setMinimumSize(QtCore.QSize(210, 40))
        self.InserNewUser_insertUserButton.setMaximumSize(QtCore.QSize(210, 40))
        self.InserNewUser_insertUserButton.setObjectName("InserNewUser_insertUserButton")
        self.InserNewUser_nameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.InserNewUser_nameInput.setGeometry(QtCore.QRect(125, 200, 550, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.InserNewUser_nameInput.setFont(font)
        self.InserNewUser_nameInput.setText("")
        self.InserNewUser_nameInput.setObjectName("InserNewUser_nameInput")
        self.InserNewUser_nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.InserNewUser_nameLabel.setGeometry(QtCore.QRect(125, 160, 550, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.InserNewUser_nameLabel.setFont(font)
        self.InserNewUser_nameLabel.setObjectName("InserNewUser_nameLabel")
        self.InserNewUser_bdayInput = QtWidgets.QLineEdit(self.centralwidget)
        self.InserNewUser_bdayInput.setGeometry(QtCore.QRect(125, 290, 550, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.InserNewUser_bdayInput.setFont(font)
        self.InserNewUser_bdayInput.setText("")
        self.InserNewUser_bdayInput.setObjectName("InserNewUser_bdayInput")
        self.InserNewUser_bdayLabel = QtWidgets.QLabel(self.centralwidget)
        self.InserNewUser_bdayLabel.setGeometry(QtCore.QRect(125, 250, 550, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.InserNewUser_bdayLabel.setFont(font)
        self.InserNewUser_bdayLabel.setObjectName("InserNewUser_bdayLabel")
        self.InserNewUser_backButton = QtWidgets.QPushButton(self.centralwidget)
        self.InserNewUser_backButton.setGeometry(QtCore.QRect(650, 390, 70, 40))
        self.InserNewUser_backButton.setMinimumSize(QtCore.QSize(70, 40))
        self.InserNewUser_backButton.setMaximumSize(QtCore.QSize(70, 40))
        self.InserNewUser_backButton.setObjectName("InserNewUser_backButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Insert new user", "MainWindow"))
        self.InserNewUser_ProgramName.setText(_translate("Insert new user", "Insert New User"))
        self.InserNewUser_insertUserButton.setText(_translate("Insert new user", "Inser new user"))
        self.InserNewUser_nameLabel.setText(_translate("Insert new user", "Legal Name:"))
        self.InserNewUser_bdayLabel.setText(_translate("Insert new user", "Birth date:"))
        self.InserNewUser_backButton.setText(_translate("Insert new user", "Back"))
